### ISSUE TITLE
Fork into xqemu org?

### ISSUE THREAD

**Issue by mborgerson** [xqemu/nxdk-rdt#13]
@JayFoxRox @espes: Do you think there is value in forking this into the organization for maintenance by the group? I don't have "owner" privileges in the xqemu org so I can't create repos, etc. there myself.

**Comment by JayFoxRox** [comment]
If anything we should transfer ownership in my opinion. I don't like this weird mechanic of forking to an org repo. It makes it harder to figure out which repo to contribute to.

**Comment by espes** [comment]
@mborgerson you can now create repos in the xqemu org

**Comment by mborgerson** [comment]
Done
